### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by tfierens** [naotaco/UwpQrCodeReaderSample#1]
Hi,

Just downloaded your sample to check it out but it crashes. I can see it initialized the camera but then bombs out on this line:

await FindQrCodeFromVideoFrame(); // capture a frame and find QR code

Here are the exception details:

System.Exception was unhandled by user code
  HResult=-1072875854
  Message=The request is invalid in the current state. (Exception from HRESULT: 0xC00D36B2)
  Source=mscorlib
  StackTrace:
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at UwpQrcodeReaderSample.MainPage.<FindQrCodeFromVideoFrame>d__25.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at UwpQrcodeReaderSample.MainPage.<<OnNavigatedTo>b__12_0>d.MoveNext()
  InnerException: 

Note that when I'm running this, the platform is set to x86 and the configuration is 'Debug'.

**Comment by naotaco** [comment]
Hi tfierens,

Thanks for reporting. I've found that sometimes it reproduced here.

After starting to display preview by calling `MediaCapture#StartPreviewAsync`, it seems that it requires some short time (~300ms on my machine) to complete initializing camera. During this time, most of operation like calling `GetPreviewFrameAsync` will be failed and Exception will be thrown.

I think `StartPreviewAsync` should not return control if there are some non-initialized device or module, but this is current behavior :(

So I have only two ideas to avoid this issue. One is waiting short time to call `CaptureTimer.Start();` or catch Exception in `FindQrCodeFromVideoFrame`. So I updated code according to the second idea; it catches the exception in first attempt, but it runs well from second time. 

Could you try on your environment with the latest code?

Thanks,
